### ISSUE TITLE
Deploy | Stage 2

### ISSUE THREAD

**Issue by Sebah7** [chas-academy/u07-weather-app-Sebah7#6]
Issue with (deploy with GitHub for CI/CD) : build succuss but page not found.

_Originally posted by @Sebah7 in https://github.com/chas-academy/u07-weather-app-Sebah7/issues/5#issuecomment-2071776618_

**Comment by Sebah7-Chas** [comment]
Deployed manually then connected to repo as it deploys without error when using GitHub directly however not succeeding in reality.
